/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import sistema.controlador.ProductoC;
import sistema.dao.ProductoD;
import sistema.modelo.CategoriaM;
import sistema.modelo.UnidadM;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlAgregarProductoContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    int nPnl, pnlActualClick;
    double precioTotal;

    ProductoC productoC = new ProductoC();
    Hover hover;

    DefaultTableModel modeloTablaProducto;

    public PnlAgregarProductoContainer() {

        //Apariencia Componentes    
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        }

        initComponents();
        this.setBorder(new EmptyBorder(20, 40, 40, 40));
        //Añanidor hover al menu
        nPnl = pnlOptionProductos.getComponentCount();
        hover = new Hover(nPnl, pnlOptionProductos);
        hover.menu(-1);

        //Controlador de producto
        productoC.mostrarCategoriaFiltroAgregar(jcCategoriaFiltro);

        try {
            tipoFiltro = 0;
            datoFiltro = "";
            this.cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlAgregarProductoContainer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código", "Categoria", "Producto", "Precio", "Unidad"};
        modeloTablaProducto = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        productoC.listarProductoTabla(modeloTablaProducto, tipoFiltro, datoFiltro);
        jtProducto.setModel(modeloTablaProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOptionProductos = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PnlProductosForm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblPrecio1 = new javax.swing.JLabel();
        jsCantidadProductoAgregar = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PnlFiltro = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtProductoFiltro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcCategoriaFiltro = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblPrecio2 = new javax.swing.JLabel();
        txtUnidadProducto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblPrecio3 = new javax.swing.JLabel();
        txtPrecioProductoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProducto = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        pnlOptionProductos.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.setMinimumSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.setOpaque(false);
        pnlOptionProductos.setPreferredSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionProductosMouseMoved(evt);
            }
        });
        pnlOptionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Selecionar");
        item0.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (2).png"))); // NOI18N
        item0.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionProductos.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("Cancelar");
        item1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionProductos.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        add(pnlOptionProductos, java.awt.BorderLayout.LINE_END);

        PnlProductosForm.setBackground(new java.awt.Color(255, 255, 255));
        PnlProductosForm.setMaximumSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setMinimumSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setOpaque(false);
        PnlProductosForm.setPreferredSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtProducto.setEnabled(false);
        txtProducto.setOpaque(false);
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("PRODUCTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 70));

        jPanel9.setBackground(new java.awt.Color(102, 153, 255));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPrecio1.setText("Cantidad");
        jPanel9.add(lblPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jsCantidadProductoAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jsCantidadProductoAgregar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jsCantidadProductoAgregar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsCantidadProductoAgregarStateChanged(evt);
            }
        });
        jPanel9.add(jsCantidadProductoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, -1));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPrecio.setText("PRECIO UNIDAD");
        jPanel5.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtPrecioProducto.setEnabled(false);
        txtPrecioProducto.setOpaque(false);
        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });
        jPanel5.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 140, -1));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCodigoProducto.setEnabled(false);
        txtCodigoProducto.setOpaque(false);
        txtCodigoProducto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoProductoCaretUpdate(evt);
            }
        });
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyTyped(evt);
            }
        });
        jPanel3.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("CODIGO");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        PnlFiltro.setMaximumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setMinimumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setOpaque(false);
        PnlFiltro.setPreferredSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProductoFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtProductoFiltro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        txtProductoFiltro.setOpaque(false);
        txtProductoFiltro.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProductoFiltroCaretUpdate(evt);
            }
        });
        jPanel7.add(txtProductoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("BUSCAR");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 20));

        PnlFiltro.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 60));

        jcCategoriaFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcCategoriaFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCategoriaFiltroItemStateChanged(evt);
            }
        });
        jcCategoriaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriaFiltroActionPerformed(evt);
            }
        });
        jcCategoriaFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcCategoriaFiltroPropertyChange(evt);
            }
        });
        jcCategoriaFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jcCategoriaFiltroVetoableChange(evt);
            }
        });
        PnlFiltro.add(jcCategoriaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 30));

        jPanel1.add(PnlFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 470, 80));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPrecio2.setText("Unidad");
        jPanel6.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        txtUnidadProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtUnidadProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtUnidadProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtUnidadProducto.setEnabled(false);
        txtUnidadProducto.setOpaque(false);
        txtUnidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadProductoKeyTyped(evt);
            }
        });
        jPanel6.add(txtUnidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, -1));

        jPanel8.setBackground(new java.awt.Color(102, 153, 255));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPrecio3.setText("PRECIO");
        jPanel8.add(lblPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        txtPrecioProductoTotal.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPrecioProductoTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioProductoTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtPrecioProductoTotal.setEnabled(false);
        txtPrecioProductoTotal.setOpaque(false);
        txtPrecioProductoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoTotalKeyTyped(evt);
            }
        });
        jPanel8.add(txtPrecioProductoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, -1));

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jtProducto.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtProducto.setGridColor(new java.awt.Color(255, 255, 255));
        jtProducto.setRowHeight(25);
        jtProducto.setSelectionBackground(new java.awt.Color(20, 110, 214));
        jtProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProducto);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PnlProductosForm.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(PnlProductosForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductoMouseClicked
        int fila = jtProducto.getSelectedRow(); // el nro de fila seleccionada

        if (fila >= 0) {

            //Botones
            desactivarBotones(1);
            hover.menu(-1);

            //Campos de formularios
            txtCodigoProducto.setText(jtProducto.getValueAt(fila, 0).toString());//Codigo de producto

//            String categoria = jtProducto.getValueAt(fila, 1).toString();
            txtProducto.setText(jtProducto.getValueAt(fila, 2).toString());//Nombre del producto

            txtPrecioProducto.setText(jtProducto.getValueAt(fila, 3).toString());//Precio unidad
            txtUnidadProducto.setText(jtProducto.getValueAt(fila, 4).toString());//Unidad de medida
            jsCantidadProductoAgregar.setValue(1);
            calcularPrecioProducto();

        }


    }//GEN-LAST:event_jtProductoMouseClicked

    private void calcularPrecioProducto() {

        precioTotal = Double.parseDouble(txtPrecioProducto.getText()) * (int) jsCantidadProductoAgregar.getValue();

        txtPrecioProductoTotal.setText(String.format("%.2f", precioTotal));
    }

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked
//        "Código", "Producto", "Unidad", "Precio", "Cantidad", "P. Venta"};
        String cantidad = String.valueOf(jsCantidadProductoAgregar.getValue());
        String precio = String.valueOf(precioTotal);

        DefaultTableModel modelo = (DefaultTableModel) PnlVentaProductoContainer.jtVentaProducto.getModel();

        String[] datos = {txtCodigoProducto.getText(),
            txtProducto.getText(),
            txtUnidadProducto.getText(),
            txtPrecioProducto.getText(),
            cantidad,
            precio
        }; // Cantidad de columnas de la tabla

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0).toString().equals(txtCodigoProducto.getText())) {

                double precioProducto = Double.parseDouble(modelo.getValueAt(i, 3).toString());

                int cantidadProductoActual = Integer.parseInt(modelo.getValueAt(i, 4).toString());
                int cantidadProducto = (int) jsCantidadProductoAgregar.getValue();
                String cantidadFinal = String.valueOf(cantidadProductoActual + cantidadProducto);

                double precioTotal = Integer.parseInt(cantidadFinal) * precioProducto;

                modelo.setValueAt(String.valueOf(cantidadFinal), i, 4);
                System.out.println(precioTotal);

                modelo.setValueAt(String.format("%.2f", precioTotal), i, 5);

                JOptionPane.showMessageDialog(null, "Cantidad actualizada");

                productoC.limpiarVariablesAgregar();
                PnlEntradaContainer.pnlVentaProducto.getComponent(0).setVisible(true);
                PnlEntradaContainer.pnlVentaProducto.getComponent(1).setVisible(false);
                PnlEntradaContainer.pnlVentaProducto.add(PnlEntradaContainer.pnlVentaProducto.getComponent(0), 0);
                PnlEntradaContainer.pnlVentaProducto.validate();

                return;
            } else {
                System.out.println("El número no existe");
            }
        }

        modelo.addRow(datos);

        productoC.limpiarVariablesAgregar();
        PnlEntradaContainer.pnlVentaProducto.getComponent(0).setVisible(true);
        PnlEntradaContainer.pnlVentaProducto.getComponent(1).setVisible(false);
        PnlEntradaContainer.pnlVentaProducto.add(PnlEntradaContainer.pnlVentaProducto.getComponent(0), 0);
        PnlEntradaContainer.pnlVentaProducto.validate();


    }//GEN-LAST:event_item0MouseClicked

    private void sumarProductoRow(JTable table) {

    }

    //Boton Actualizar
    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        if (item1.isEnabled()) {

            productoC.limpiarVariablesAgregar();
            PnlEntradaContainer.pnlVentaProducto.getComponent(0).setVisible(true);
            PnlEntradaContainer.pnlVentaProducto.getComponent(1).setVisible(false);
            PnlEntradaContainer.pnlVentaProducto.add(PnlEntradaContainer.pnlVentaProducto.getComponent(0), 0);
            PnlEntradaContainer.pnlVentaProducto.validate();

        }
    }//GEN-LAST:event_item1MouseClicked

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
//        hoverMenu(0);
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
//        hoverMenu(1);
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void pnlOptionProductosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionProductosMouseMoved
//        hoverMenu(-1);
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionProductosMouseMoved

    private void jcCategoriaFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroPropertyChange

    }//GEN-LAST:event_jcCategoriaFiltroPropertyChange

    private void jcCategoriaFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroItemStateChanged

    }//GEN-LAST:event_jcCategoriaFiltroItemStateChanged

    private void jcCategoriaFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jcCategoriaFiltroVetoableChange

    }//GEN-LAST:event_jcCategoriaFiltroVetoableChange

    private void jcCategoriaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroActionPerformed
        try {
            if (jcCategoriaFiltro.getSelectedIndex() == 0) {
                tipoFiltro = 0;
                datoFiltro = "";
            } else {
                tipoFiltro = 1;
                datoFiltro = PnlAgregarProductoContainer.jcCategoriaFiltro.getItemAt(jcCategoriaFiltro.getSelectedIndex()).getDESCAT();
            }
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlAgregarProductoContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcCategoriaFiltroActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.' || txtPrecioProducto.getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void txtCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyTyped
//        char caracter = evt.getKeyChar();
//        if (txtCodigoProducto.getText().length() >= 4) {
//            evt.consume();
//        }
//        if (!Character.isLetterOrDigit(evt.getKeyChar())) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtCodigoProductoKeyTyped

    private void txtCodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyReleased
//        String codigo = txtCodigoProducto.getText();
//        txtCodigoProducto.setText(codigo.substring(0, codigo.length()).toUpperCase());
    }//GEN-LAST:event_txtCodigoProductoKeyReleased

    private void txtCodigoProductoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoProductoCaretUpdate

    }//GEN-LAST:event_txtCodigoProductoCaretUpdate

    private void txtProductoFiltroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProductoFiltroCaretUpdate
        jcCategoriaFiltro.setSelectedIndex(0);
        try {
            tipoFiltro = 2;
            datoFiltro = txtProductoFiltro.getText();
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlAgregarProductoContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtProductoFiltroCaretUpdate

    private void txtUnidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadProductoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadProductoKeyTyped

    private void txtPrecioProductoTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoTotalKeyTyped

    private void jsCantidadProductoAgregarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsCantidadProductoAgregarStateChanged
        calcularPrecioProducto();
    }//GEN-LAST:event_jsCantidadProductoAgregarStateChanged

    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(true);

                break;

            case 2:
                item0.setEnabled(true);
                item1.setEnabled(true);
                break;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFiltro;
    private javax.swing.JPanel PnlProductosForm;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<CategoriaM> jcCategoriaFiltro;
    public static javax.swing.JSpinner jsCantidadProductoAgregar;
    private javax.swing.JTable jtProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JPanel pnlOptionProductos;
    public static javax.swing.JTextField txtCodigoProducto;
    public static javax.swing.JTextField txtPrecioProducto;
    public static javax.swing.JTextField txtPrecioProductoTotal;
    public static javax.swing.JTextField txtProducto;
    public static javax.swing.JTextField txtProductoFiltro;
    public static javax.swing.JTextField txtUnidadProducto;
    // End of variables declaration//GEN-END:variables
}
