/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.event.KeyEvent;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import sistema.controlador.EmpresaC;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlEmpresaContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    int nPnl, pnlActualClick;

    DefaultTableModel modeloTablaEmpresa;

    EmpresaC empresaC = new EmpresaC();
    Hover hover;

    public PnlEmpresaContainer() {

        initComponents();
        txtCodigoEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        //Añanidor hover al menu
        nPnl = pnlOptionEmpresa.getComponentCount();
        hover = new Hover(nPnl, pnlOptionEmpresa);
        hover.menu(-1);
        try {
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlEmpresaContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBorder(new EmptyBorder(20, 40, 40, 40));
    }

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código","Razon Social" ,"Nombre", "RUC", "Activo"};

        modeloTablaEmpresa = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
//        productoD.listarProductoTabla(modeloTablaProducto, tipoFiltro, datoFiltro);
        empresaC.listarEmpresaTabla(modeloTablaEmpresa, tipoFiltro, datoFiltro);
        jtEmpresa.setModel(modeloTablaEmpresa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrupoGenero = new javax.swing.ButtonGroup();
        pnlUsuariosForm = new javax.swing.JPanel();
        pnlCodigo = new javax.swing.JPanel();
        txtCodigoEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        pnlApellido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtRazonSocialEmpresa = new javax.swing.JTextField();
        pnlDni = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtRucEmpresa = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        jckEstadoEmpresa = new javax.swing.JCheckBox();
        pnlOptionEmpresa = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlContainerFiltro = new javax.swing.JPanel();
        PnlFiltro = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtEmpresaFiltro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcEmpresaFiltro = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpresa = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        pnlUsuariosForm.setMaximumSize(new java.awt.Dimension(570, 400));
        pnlUsuariosForm.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlUsuariosForm.setOpaque(false);
        pnlUsuariosForm.setPreferredSize(new java.awt.Dimension(550, 300));
        pnlUsuariosForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCodigo.setBackground(new java.awt.Color(102, 153, 255));
        pnlCodigo.setOpaque(false);
        pnlCodigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoEmpresa.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCodigoEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCodigoEmpresa.setEnabled(false);
        txtCodigoEmpresa.setOpaque(false);
        pnlCodigo.add(txtCodigoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Codigo");
        pnlCodigo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUsuariosForm.add(pnlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        pnlNombre.setOpaque(false);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        pnlNombre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaActionPerformed(evt);
            }
        });
        pnlNombre.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, 30));

        pnlUsuariosForm.add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 310, -1));

        pnlApellido.setOpaque(false);
        pnlApellido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Razon Social");
        pnlApellido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtRazonSocialEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRazonSocialEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        txtRazonSocialEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtRazonSocialEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialEmpresaActionPerformed(evt);
            }
        });
        pnlApellido.add(txtRazonSocialEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, 30));

        pnlUsuariosForm.add(pnlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, -1));

        pnlDni.setOpaque(false);
        pnlDni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("RUC");
        pnlDni.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtRucEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRucEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        txtRucEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtRucEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucEmpresaActionPerformed(evt);
            }
        });
        txtRucEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucEmpresaKeyTyped(evt);
            }
        });
        pnlDni.add(txtRucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 30));

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarPersona.setBorder(null);
        btnBuscarPersona.setBorderPainted(false);
        btnBuscarPersona.setContentAreaFilled(false);
        btnBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseClicked(evt);
            }
        });
        pnlDni.add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 40, 40));

        pnlUsuariosForm.add(pnlDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, -1));

        jckEstadoEmpresa.setSelected(true);
        jckEstadoEmpresa.setText("Activo");
        jckEstadoEmpresa.setOpaque(false);
        pnlUsuariosForm.add(jckEstadoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 120, 60));

        add(pnlUsuariosForm, java.awt.BorderLayout.CENTER);

        pnlOptionEmpresa.setBackground(new java.awt.Color(204, 102, 255));
        pnlOptionEmpresa.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionEmpresa.setOpaque(false);
        pnlOptionEmpresa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionEmpresaMouseMoved(evt);
            }
        });
        pnlOptionEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Guardar");
        item0.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (2).png"))); // NOI18N
        item0.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionEmpresa.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setText("Editar");
        item1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag7.png"))); // NOI18N
        item1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionEmpresa.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        item2.setBackground(new java.awt.Color(204, 204, 204));
        item2.setEnabled(false);
        item2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item2MouseMoved(evt);
            }
        });
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });
        item2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setText("Eliminar");
        item2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        pnlOptionEmpresa.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        item3.setBackground(new java.awt.Color(204, 204, 204));
        item3.setEnabled(false);
        item3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item3MouseMoved(evt);
            }
        });
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });
        item3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel23.setText("Nuevo");
        item3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (1).png"))); // NOI18N
        item3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 30, 50));

        pnlOptionEmpresa.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 50));

        item4.setBackground(new java.awt.Color(204, 204, 204));
        item4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item4MouseMoved(evt);
            }
        });
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });
        item4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel25.setText("Imprimir");
        item4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (6).png"))); // NOI18N
        item4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionEmpresa.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 50));

        jPanel1.setOpaque(false);
        pnlOptionEmpresa.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 30));

        add(pnlOptionEmpresa, java.awt.BorderLayout.LINE_END);

        pnlContainerFiltro.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlContainerFiltro.setMinimumSize(new java.awt.Dimension(800, 250));
        pnlContainerFiltro.setOpaque(false);
        pnlContainerFiltro.setPreferredSize(new java.awt.Dimension(800, 250));
        pnlContainerFiltro.setLayout(new java.awt.BorderLayout());

        PnlFiltro.setMaximumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setMinimumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setOpaque(false);
        PnlFiltro.setPreferredSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmpresaFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtEmpresaFiltro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        txtEmpresaFiltro.setOpaque(false);
        txtEmpresaFiltro.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmpresaFiltroCaretUpdate(evt);
            }
        });
        jPanel7.add(txtEmpresaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("BUSCAR");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 20));

        PnlFiltro.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 60));

        jcEmpresaFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcEmpresaFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione filtro", "Nombre", "Apellido", "Dni", "Inactivos" }));
        jcEmpresaFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcEmpresaFiltroItemStateChanged(evt);
            }
        });
        jcEmpresaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEmpresaFiltroActionPerformed(evt);
            }
        });
        jcEmpresaFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcEmpresaFiltroPropertyChange(evt);
            }
        });
        jcEmpresaFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jcEmpresaFiltroVetoableChange(evt);
            }
        });
        PnlFiltro.add(jcEmpresaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 30));

        pnlContainerFiltro.add(PnlFiltro, java.awt.BorderLayout.PAGE_START);

        jtEmpresa.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtEmpresa.setGridColor(new java.awt.Color(255, 255, 255));
        jtEmpresa.setRowHeight(25);
        jtEmpresa.setSelectionBackground(new java.awt.Color(20, 110, 214));
        jtEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEmpresa);

        pnlContainerFiltro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlContainerFiltro, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaActionPerformed

    private void txtRazonSocialEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialEmpresaActionPerformed

    private void txtRucEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucEmpresaActionPerformed

    private void jcEmpresaFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcEmpresaFiltroItemStateChanged

    }//GEN-LAST:event_jcEmpresaFiltroItemStateChanged

    private void jcEmpresaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEmpresaFiltroActionPerformed
        try {
            if (jcEmpresaFiltro.getSelectedIndex() == 0) {
                tipoFiltro = 0;
                datoFiltro = "";
            } else {
                tipoFiltro = jcEmpresaFiltro.getSelectedIndex();
            }
            filtrar();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcEmpresaFiltroActionPerformed

    private void filtrar() {
        try {
            datoFiltro = txtEmpresaFiltro.getText();
            txtEmpresaFiltro.requestFocus();
            txtEmpresaFiltro.setText("");

            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jcEmpresaFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcEmpresaFiltroPropertyChange

    }//GEN-LAST:event_jcEmpresaFiltroPropertyChange

    private void jcEmpresaFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jcEmpresaFiltroVetoableChange

    }//GEN-LAST:event_jcEmpresaFiltroVetoableChange

    private void jtEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmpresaMouseClicked

        int fila = jtEmpresa.getSelectedRow(); // el nro de fila seleccionada

        if (fila >= 0) {

            //Botones
            desactivarBotones(2);
            hover.menu(-1);

            //Campos de formularios
            txtCodigoEmpresa.setText(jtEmpresa.getValueAt(fila, 0).toString());
            txtRazonSocialEmpresa.setText(jtEmpresa.getValueAt(fila, 1).toString());
            
            if (!txtNombreEmpresa.getText().equals("")) {
                txtNombreEmpresa.setText(jtEmpresa.getValueAt(fila, 2).toString());
            }

            txtRucEmpresa.setText(jtEmpresa.getValueAt(fila, 3).toString());

            if ("A".equals(jtEmpresa.getValueAt(fila, 4).toString())) {
                jckEstadoEmpresa.setSelected(true);
            } else {
                jckEstadoEmpresa.setSelected(false);
            }

        }


    }//GEN-LAST:event_jtEmpresaMouseClicked

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked
        if (item0.isEnabled()) {
            try {
                if (!empresaC.validarExistenciaEmpresa(txtRucEmpresa.getText())) {
                    if (empresaC.validar()) {
                        empresaC.cargarVariables();
                        empresaC.guardarEmpresa();
                        cargarTabla();
                        empresaC.limpiarVariables();
                    }
                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlEmpresaContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item0MouseClicked

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        if (item1.isEnabled()) {
            try {

                if (empresaC.validar()) {
                    empresaC.cargarVariables();
                    empresaC.editarEmpresa();
                    cargarTabla();
                    empresaC.limpiarVariables();
                    desactivarBotones(1);
                    hover.menu(-1);

                }
            } catch (Exception ex) {
                Logger.getLogger(PnlEmpresaContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseMoved
        hover.menu(2);
    }//GEN-LAST:event_item2MouseMoved

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        if (item2.isEnabled()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Seguro de eliminar",
                    "Eliminación del registro",
                    JOptionPane.OK_CANCEL_OPTION);

            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    if (empresaC.validar()) {
                        empresaC.cargarVariables();
                        empresaC.eliminarEmpresa();
                        cargarTabla();
                        empresaC.limpiarVariables();
                        desactivarBotones(1);
                        hover.menu(-1);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(PnlEmpresaContainer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_item2MouseClicked

    private void item3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseMoved
        hover.menu(3);
    }//GEN-LAST:event_item3MouseMoved

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        if (item3.isEnabled()) {
            empresaC.limpiarVariables();
            desactivarBotones(1);
            hover.menu(-1);
        }
    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseMoved
        hover.menu(4);
    }//GEN-LAST:event_item4MouseMoved

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        empresaC.reporteEmpresa();
    }//GEN-LAST:event_item4MouseClicked

    private void pnlOptionEmpresaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionEmpresaMouseMoved
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionEmpresaMouseMoved


    private void btnBuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseClicked
        if (txtRucEmpresa.getText().length() >= 11) {
            empresaC.resEmpresa(txtRucEmpresa.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese RUC (11 digitos)");
        }
    }//GEN-LAST:event_btnBuscarPersonaMouseClicked

    private void txtEmpresaFiltroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmpresaFiltroCaretUpdate

        try {
            datoFiltro = txtEmpresaFiltro.getText();
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlEmpresaContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtEmpresaFiltroCaretUpdate

    private void txtRucEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucEmpresaKeyTyped
        char caracter = evt.getKeyChar();
        if (txtRucEmpresa.getText().length() >= 11) {
            evt.consume();
        }

        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRucEmpresaKeyTyped

    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(true);
                txtCodigoEmpresa.setEnabled(true);

                break;

            case 2:
                item0.setEnabled(false);
                item1.setEnabled(true);
                item2.setEnabled(true);
                item3.setEnabled(true);
                item4.setEnabled(false);
                txtCodigoEmpresa.setEnabled(false);

                break;

            case 3:
                item0.setEnabled(false);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(false);
                txtCodigoEmpresa.setEnabled(false);
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFiltro;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox jcEmpresaFiltro;
    public static javax.swing.JCheckBox jckEstadoEmpresa;
    private javax.swing.JTable jtEmpresa;
    private javax.swing.JPanel pnlApellido;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPanel pnlContainerFiltro;
    private javax.swing.JPanel pnlDni;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlOptionEmpresa;
    private javax.swing.JPanel pnlUsuariosForm;
    public static javax.swing.ButtonGroup rdGrupoGenero;
    public static javax.swing.JTextField txtCodigoEmpresa;
    public static javax.swing.JTextField txtEmpresaFiltro;
    public static javax.swing.JTextField txtNombreEmpresa;
    public static javax.swing.JTextField txtRazonSocialEmpresa;
    public static javax.swing.JTextField txtRucEmpresa;
    // End of variables declaration//GEN-END:variables
}
