/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.BorderLayout;

/**
 *
 * @author Jose Luis
 */
public class PnlEntradaContainer extends javax.swing.JPanel {

    /**
     * Creates new form PnlEntradaContainer
     */
    
    PnlVentaProductoContainer pnlVentaProductoContainer = new PnlVentaProductoContainer();
    PnlVentasContainer pnlVentaContainer = new PnlVentasContainer();
    PnlAgregarProductoContainer pnlAgregarProductoContainer = new PnlAgregarProductoContainer();
    
    public PnlEntradaContainer() {
        initComponents();
        pnlVentaProducto.add(pnlVentaProductoContainer);
        pnlVentaProducto.add(pnlAgregarProductoContainer);
        pnlVentaProducto.add(pnlVentaProducto.getComponent(0), 0);
        pnlVentaProducto.validate();
        
        
        pnlVentas.add(pnlVentaContainer, BorderLayout.CENTER);
        pnlVentas.validate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtmVentas = new javax.swing.JTabbedPane();
        pnlVentas = new javax.swing.JPanel();
        pnlVentaProducto = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        jtmVentas.setToolTipText("");
        jtmVentas.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        pnlVentas.setLayout(new java.awt.BorderLayout());
        jtmVentas.addTab("Ventas", pnlVentas);

        pnlVentaProducto.setLayout(new java.awt.BorderLayout());
        jtmVentas.addTab("Ventas Producto", pnlVentaProducto);

        add(jtmVentas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane jtmVentas;
    public static javax.swing.JPanel pnlVentaProducto;
    public static javax.swing.JPanel pnlVentas;
    // End of variables declaration//GEN-END:variables
}
