/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import sistema.controlador.ProductoC;
import sistema.dao.Conexion;
import sistema.dao.ProductoD;
import sistema.modelo.CategoriaM;
import sistema.modelo.UnidadM;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlProductosContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    int nPnl, pnlActualClick;

    ProductoC productoC = new ProductoC();
    Hover hover;

    DefaultTableModel modeloTablaProducto;

    public PnlProductosContainer() {

        //Apariencia Componentes    
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        }

        initComponents();
        this.setBorder(new EmptyBorder(20, 40, 40, 40));
        //Añanidor hover al menu
        nPnl = pnlOptionProductos.getComponentCount();
        hover = new Hover(nPnl, pnlOptionProductos);
        hover.menu(-1);

        //Controlador de producto
        productoC.mostrarUnidad(jcUnidadMedida);
        productoC.mostrarCategoria(jcCategoria, jcCategoriaFiltro);

        try {
            tipoFiltro = 0;
            datoFiltro = "";
            this.cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código", "Categoria", "Producto", "Precio", "Unidad"};
        modeloTablaProducto = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        productoC.listarProductoTabla(modeloTablaProducto, tipoFiltro, datoFiltro);
        jtProducto.setModel(modeloTablaProducto);
        PnlAgregarProductoContainer.jcCategoriaFiltro.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainerFiltro = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        PnlFiltro = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtProductoFiltro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcCategoriaFiltro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProducto = new javax.swing.JTable();
        pnlOptionProductos = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PnlProductosForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcUnidadMedida = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcCategoria = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        pnlContainerFiltro.setMaximumSize(new java.awt.Dimension(570, 300));
        pnlContainerFiltro.setMinimumSize(new java.awt.Dimension(570, 300));
        pnlContainerFiltro.setOpaque(false);
        pnlContainerFiltro.setPreferredSize(new java.awt.Dimension(570, 300));
        pnlContainerFiltro.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(102, 153, 255));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlContainerFiltro.add(jPanel8, java.awt.BorderLayout.LINE_END);

        PnlFiltro.setMaximumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setMinimumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setOpaque(false);
        PnlFiltro.setPreferredSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProductoFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtProductoFiltro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        txtProductoFiltro.setOpaque(false);
        txtProductoFiltro.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProductoFiltroCaretUpdate(evt);
            }
        });
        jPanel7.add(txtProductoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("BUSCAR");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 20));

        PnlFiltro.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 60));

        jcCategoriaFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcCategoriaFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCategoriaFiltroItemStateChanged(evt);
            }
        });
        jcCategoriaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriaFiltroActionPerformed(evt);
            }
        });
        jcCategoriaFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcCategoriaFiltroPropertyChange(evt);
            }
        });
        jcCategoriaFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jcCategoriaFiltroVetoableChange(evt);
            }
        });
        PnlFiltro.add(jcCategoriaFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 30));

        pnlContainerFiltro.add(PnlFiltro, java.awt.BorderLayout.PAGE_START);

        jtProducto.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtProducto.setGridColor(new java.awt.Color(255, 255, 255));
        jtProducto.setRowHeight(25);
        jtProducto.setSelectionBackground(new java.awt.Color(20, 110, 214));
        jtProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProducto);

        pnlContainerFiltro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlContainerFiltro, java.awt.BorderLayout.PAGE_END);

        pnlOptionProductos.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.setMinimumSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.setOpaque(false);
        pnlOptionProductos.setPreferredSize(new java.awt.Dimension(150, 300));
        pnlOptionProductos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionProductosMouseMoved(evt);
            }
        });
        pnlOptionProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Guardar");
        item0.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (2).png"))); // NOI18N
        item0.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionProductos.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("Editar");
        item1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag7.png"))); // NOI18N
        item1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionProductos.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        item2.setBackground(new java.awt.Color(204, 204, 204));
        item2.setEnabled(false);
        item2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item2MouseMoved(evt);
            }
        });
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });
        item2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setText("Eliminar");
        item2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        pnlOptionProductos.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        item3.setBackground(new java.awt.Color(204, 204, 204));
        item3.setEnabled(false);
        item3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item3MouseMoved(evt);
            }
        });
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });
        item3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel18.setText("Nuevo");
        item3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (1).png"))); // NOI18N
        item3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 30, 50));

        pnlOptionProductos.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 50));

        item4.setBackground(new java.awt.Color(204, 204, 204));
        item4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item4MouseMoved(evt);
            }
        });
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });
        item4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel20.setText("Imprimir");
        item4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (6).png"))); // NOI18N
        item4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionProductos.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 50));

        add(pnlOptionProductos, java.awt.BorderLayout.LINE_END);

        PnlProductosForm.setBackground(new java.awt.Color(255, 255, 255));
        PnlProductosForm.setMaximumSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setMinimumSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setPreferredSize(new java.awt.Dimension(570, 400));
        PnlProductosForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCodigoProducto.setEnabled(false);
        txtCodigoProducto.setOpaque(false);
        txtCodigoProducto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoProductoCaretUpdate(evt);
            }
        });
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyTyped(evt);
            }
        });
        jPanel3.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("CODIGO");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        PnlProductosForm.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtProducto.setOpaque(false);
        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel1.setText("PRODUCTO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        PnlProductosForm.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, -1));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("UNIDAD DE MEDIDA");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jcUnidadMedida.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel4.add(jcUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        PnlProductosForm.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 230, 60));

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecio.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblPrecio.setText("PRECIO");
        jPanel5.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecioProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtPrecioProducto.setOpaque(false);
        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });
        jPanel5.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 30));

        PnlProductosForm.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 60));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("CATEGORIA");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jcCategoria.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPanel6.add(jcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 30));

        PnlProductosForm.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 230, 60));

        add(PnlProductosForm, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductoMouseClicked
        int fila = jtProducto.getSelectedRow(); // el nro de fila seleccionada

        if (fila >= 0) {

            //Botones
            desactivarBotones(2);
            hover.menu(-1);

            //Campos de formularios
            txtCodigoProducto.setText(jtProducto.getValueAt(fila, 0).toString());

            String categoria = jtProducto.getValueAt(fila, 1).toString();
            for (int index = 0; index < jcCategoria.getItemCount(); index++) {
                if (jcCategoria.getItemAt(index).getDESCAT().equals(categoria)) {
                    jcCategoria.setSelectedIndex(index);
                    break;
                };
            }

            txtProducto.setText(jtProducto.getValueAt(fila, 2).toString());

            txtPrecioProducto.setText(jtProducto.getValueAt(fila, 3).toString());

            String unidad = jtProducto.getValueAt(fila, 4).toString();
            for (int index = 0; index < jcUnidadMedida.getItemCount(); index++) {
                if (jcUnidadMedida.getItemAt(index).getDESUNI().equals(unidad)) {
                    jcUnidadMedida.setSelectedIndex(index);
                    break;
                };
            }

        }


    }//GEN-LAST:event_jtProductoMouseClicked

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked

        if (item0.isEnabled()) {
            try {
                if (productoC.validar()) {
                    productoC.CargarVariables();
                    productoC.guardarProducto();
                    cargarTabla();
                    productoC.limpiarVariables();
                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_item0MouseClicked

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        if (item2.isEnabled()) {
            try {
                if (productoC.validar()) {
                    productoC.CargarVariables();
                    productoC.eliminarProducto();
                    cargarTabla();
                    productoC.limpiarVariables();
                    desactivarBotones(1);

                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item2MouseClicked

    //Boton Actualizar
    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        if (item1.isEnabled()) {
            try {
                if (productoC.validar()) {
                    productoC.CargarVariables();
                    productoC.editarProducto();
                    cargarTabla();
                    productoC.limpiarVariables();
                    desactivarBotones(1);
                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item1MouseClicked

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        if (item3.isEnabled()) {
            productoC.limpiarVariables();
            desactivarBotones(1);
            hover.menu(-1);
        }
    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        productoC.reporteProducto();
    }//GEN-LAST:event_item4MouseClicked

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
//        hoverMenu(0);
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
//        hoverMenu(1);
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void item2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseMoved
//        hoverMenu(2);
        hover.menu(2);
    }//GEN-LAST:event_item2MouseMoved

    private void item3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseMoved
//        hoverMenu(3);
        hover.menu(3);
    }//GEN-LAST:event_item3MouseMoved

    private void item4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseMoved
//        hoverMenu(4);
        hover.menu(4);
    }//GEN-LAST:event_item4MouseMoved

    private void pnlOptionProductosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionProductosMouseMoved
//        hoverMenu(-1);
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionProductosMouseMoved

    private void jcCategoriaFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroPropertyChange

    }//GEN-LAST:event_jcCategoriaFiltroPropertyChange

    private void jcCategoriaFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroItemStateChanged

    }//GEN-LAST:event_jcCategoriaFiltroItemStateChanged

    private void jcCategoriaFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jcCategoriaFiltroVetoableChange

    }//GEN-LAST:event_jcCategoriaFiltroVetoableChange

    private void jcCategoriaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriaFiltroActionPerformed
        try {
            if (jcCategoriaFiltro.getSelectedIndex() == 0) {
                tipoFiltro = 0;
                datoFiltro = "";
            } else {
                tipoFiltro = 1;
                datoFiltro = PnlProductosContainer.jcCategoriaFiltro.getItemAt(jcCategoriaFiltro.getSelectedIndex()).getDESCAT();
            }
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcCategoriaFiltroActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.' || txtPrecioProducto.getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void txtCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyTyped
//        char caracter = evt.getKeyChar();
//        if (txtCodigoProducto.getText().length() >= 4) {
//            evt.consume();
//        }
//        if (!Character.isLetterOrDigit(evt.getKeyChar())) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtCodigoProductoKeyTyped

    private void txtCodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyReleased
//        String codigo = txtCodigoProducto.getText();
//        txtCodigoProducto.setText(codigo.substring(0, codigo.length()).toUpperCase());
    }//GEN-LAST:event_txtCodigoProductoKeyReleased

    private void txtCodigoProductoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoProductoCaretUpdate

    }//GEN-LAST:event_txtCodigoProductoCaretUpdate

    private void txtProductoFiltroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProductoFiltroCaretUpdate
        jcCategoriaFiltro.setSelectedIndex(0);
        try {
            tipoFiltro = 2;
            datoFiltro = txtProductoFiltro.getText();
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlProductosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtProductoFiltroCaretUpdate

    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(true);
                txtCodigoProducto.setEnabled(false);

                break;

            case 2:
                item0.setEnabled(false);
                item1.setEnabled(true);
                item2.setEnabled(true);
                item3.setEnabled(true);
                item4.setEnabled(false);
                txtCodigoProducto.setEnabled(false);

                break;

            case 3:
                item0.setEnabled(false);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(false);
                txtCodigoProducto.setEnabled(false);
                break;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFiltro;
    private javax.swing.JPanel PnlProductosForm;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<CategoriaM> jcCategoria;
    public static javax.swing.JComboBox<CategoriaM> jcCategoriaFiltro;
    public static javax.swing.JComboBox<UnidadM> jcUnidadMedida;
    private javax.swing.JTable jtProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel pnlContainerFiltro;
    private javax.swing.JPanel pnlOptionProductos;
    public static javax.swing.JTextField txtCodigoProducto;
    public static javax.swing.JTextField txtPrecioProducto;
    public static javax.swing.JTextField txtProducto;
    public static javax.swing.JTextField txtProductoFiltro;
    // End of variables declaration//GEN-END:variables
}
