/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import sistema.controlador.UsuarioC;
import sistema.dao.UbigeoD;
import sistema.modelo.UbigeoM;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlUsuariosContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    int nPnl, pnlActualClick;

    UsuarioC usuarioC = new UsuarioC();
    UbigeoD ubigeoD = new UbigeoD();
    Hover hover;

    DefaultTableModel modeloTablaUsuario;

    public PnlUsuariosContainer() {
        initComponents();
        desactivarBotones(1);
        txtCodigoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        //Añanidor hover al menu
        nPnl = pnlOptionPersona.getComponentCount();
        hover = new Hover(nPnl, pnlOptionPersona);
        hover.menu(-1);

        txtUbigeoUsuario.setVisible(false);

        try {
            //combo departamento
            ubigeoD.listarDepartamentoUbigeo(jcDepartamentoUsuario);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar los departementos", "Error", 1);
        }

        this.setBorder(new EmptyBorder(20, 40, 40, 40));

        try {
            tipoFiltro = 0;
            datoFiltro = "";
            this.cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrupoGenero = new javax.swing.ButtonGroup();
        pnlUsuariosForm = new javax.swing.JPanel();
        pnlCodigo = new javax.swing.JPanel();
        txtCodigoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        pnlApellido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoUsuario = new javax.swing.JTextField();
        pnlDni = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDniUsuario = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        pnlUbicacion = new javax.swing.JPanel();
        jcDepartamentoUsuario = new javax.swing.JComboBox<>();
        jcDistritoUsuario = new javax.swing.JComboBox<>();
        jcProvinciaUsuario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pnlGenero = new javax.swing.JPanel();
        rdMasculinoUsuario = new javax.swing.JRadioButton();
        rdFemeninoUsuario = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        pnlTelefono = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefonoUsuario = new javax.swing.JTextField();
        pnlLogin = new javax.swing.JPanel();
        pnlRuc1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuarioUsuario = new javax.swing.JTextField();
        pnlRuc2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtContraseñaUsuario = new javax.swing.JPasswordField();
        pnlApellido1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDireccionUsuario = new javax.swing.JTextField();
        pnlFechaNacimiento = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcaNacimientoUsuario = new com.toedter.calendar.JDateChooser();
        btnCredencialLogin = new javax.swing.JButton();
        txtUbigeoUsuario = new javax.swing.JLabel();
        pnlOptionPersona = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlContainerFiltro = new javax.swing.JPanel();
        PnlFiltro = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtTextoFiltroUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcUsuarioFiltro = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        pnlUsuariosForm.setMaximumSize(new java.awt.Dimension(570, 400));
        pnlUsuariosForm.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlUsuariosForm.setOpaque(false);
        pnlUsuariosForm.setPreferredSize(new java.awt.Dimension(550, 300));
        pnlUsuariosForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCodigo.setBackground(new java.awt.Color(102, 153, 255));
        pnlCodigo.setOpaque(false);
        pnlCodigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtCodigoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCodigoUsuario.setEnabled(false);
        txtCodigoUsuario.setOpaque(false);
        pnlCodigo.add(txtCodigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Codigo");
        pnlCodigo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUsuariosForm.add(pnlCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        pnlNombre.setOpaque(false);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        pnlNombre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        pnlNombre.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlUsuariosForm.add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        pnlApellido.setOpaque(false);
        pnlApellido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");
        pnlApellido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtApellidoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtApellidoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtApellidoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoUsuarioActionPerformed(evt);
            }
        });
        pnlApellido.add(txtApellidoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlUsuariosForm.add(pnlApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 180, -1));

        pnlDni.setOpaque(false);
        pnlDni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("DNI");
        pnlDni.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtDniUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDniUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtDniUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtDniUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniUsuarioActionPerformed(evt);
            }
        });
        txtDniUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniUsuarioKeyTyped(evt);
            }
        });
        pnlDni.add(txtDniUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 30));

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscarPersona.setBorder(null);
        btnBuscarPersona.setContentAreaFilled(false);
        btnBuscarPersona.setFocusPainted(false);
        btnBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseClicked(evt);
            }
        });
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });
        pnlDni.add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 40, 40));

        pnlUsuariosForm.add(pnlDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, -1));

        pnlUbicacion.setOpaque(false);
        pnlUbicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcDepartamentoUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcDepartamentoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDepartamentoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDepartamentoUsuarioItemStateChanged(evt);
            }
        });
        jcDepartamentoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcDepartamentoUsuarioMouseClicked(evt);
            }
        });
        jcDepartamentoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDepartamentoUsuarioActionPerformed(evt);
            }
        });
        pnlUbicacion.add(jcDepartamentoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 30));

        jcDistritoUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcDistritoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDistritoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDistritoUsuarioItemStateChanged(evt);
            }
        });
        jcDistritoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDistritoUsuarioActionPerformed(evt);
            }
        });
        pnlUbicacion.add(jcDistritoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 140, 30));

        jcProvinciaUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcProvinciaUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcProvinciaUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcProvinciaUsuarioItemStateChanged(evt);
            }
        });
        pnlUbicacion.add(jcProvinciaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Ubicación");
        pnlUbicacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        pnlUsuariosForm.add(pnlUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 160));

        pnlGenero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        pnlGenero.setOpaque(false);
        pnlGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdGrupoGenero.add(rdMasculinoUsuario);
        rdMasculinoUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rdMasculinoUsuario.setText("Masculino");
        rdMasculinoUsuario.setActionCommand("M");
        rdMasculinoUsuario.setOpaque(false);
        rdMasculinoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMasculinoUsuarioActionPerformed(evt);
            }
        });
        pnlGenero.add(rdMasculinoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        rdGrupoGenero.add(rdFemeninoUsuario);
        rdFemeninoUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rdFemeninoUsuario.setText("Femenino");
        rdFemeninoUsuario.setActionCommand("F");
        rdFemeninoUsuario.setOpaque(false);
        pnlGenero.add(rdFemeninoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("Genero");
        pnlGenero.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        pnlUsuariosForm.add(pnlGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 180, 70));

        pnlTelefono.setOpaque(false);
        pnlTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setText("Telefono");
        pnlTelefono.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        txtTelefonoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefonoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefonoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtTelefonoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoUsuarioActionPerformed(evt);
            }
        });
        txtTelefonoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoUsuarioKeyTyped(evt);
            }
        });
        pnlTelefono.add(txtTelefonoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 30));

        pnlUsuariosForm.add(pnlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, -1));

        pnlLogin.setOpaque(false);
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRuc1.setOpaque(false);
        pnlRuc1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("Usuario");
        pnlRuc1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtUsuarioUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuarioUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuarioUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtUsuarioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioUsuarioActionPerformed(evt);
            }
        });
        pnlRuc1.add(txtUsuarioUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlLogin.add(pnlRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRuc2.setOpaque(false);
        pnlRuc2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setText("Contraseña");
        pnlRuc2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtContraseñaUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtContraseñaUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        pnlRuc2.add(txtContraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlLogin.add(pnlRuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        pnlUsuariosForm.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 390, 60));

        pnlApellido1.setOpaque(false);
        pnlApellido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Dirección");
        pnlApellido1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtDireccionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccionUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccionUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtDireccionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionUsuarioActionPerformed(evt);
            }
        });
        pnlApellido1.add(txtDireccionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlUsuariosForm.add(pnlApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, 60));

        pnlFechaNacimiento.setBackground(new java.awt.Color(102, 153, 255));
        pnlFechaNacimiento.setOpaque(false);
        pnlFechaNacimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setText("Fecha nacimento");
        pnlFechaNacimiento.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));
        pnlFechaNacimiento.add(jcaNacimientoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 30));

        pnlUsuariosForm.add(pnlFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 60));

        btnCredencialLogin.setText("Editar credenciales");
        btnCredencialLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCredencialLoginMouseClicked(evt);
            }
        });
        pnlUsuariosForm.add(btnCredencialLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 343, -1, 50));
        pnlUsuariosForm.add(txtUbigeoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 70, 20));

        add(pnlUsuariosForm, java.awt.BorderLayout.CENTER);

        pnlOptionPersona.setBackground(new java.awt.Color(204, 102, 255));
        pnlOptionPersona.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionPersona.setOpaque(false);
        pnlOptionPersona.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionPersonaMouseMoved(evt);
            }
        });
        pnlOptionPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Guardar");
        item0.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (2).png"))); // NOI18N
        item0.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setText("Editar");
        item1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag7.png"))); // NOI18N
        item1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        item2.setBackground(new java.awt.Color(204, 204, 204));
        item2.setEnabled(false);
        item2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item2MouseMoved(evt);
            }
        });
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });
        item2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setText("Eliminar");
        item2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        pnlOptionPersona.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        item3.setBackground(new java.awt.Color(204, 204, 204));
        item3.setEnabled(false);
        item3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item3MouseMoved(evt);
            }
        });
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });
        item3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel23.setText("Nuevo");
        item3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (1).png"))); // NOI18N
        item3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 30, 50));

        pnlOptionPersona.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 50));

        item4.setBackground(new java.awt.Color(204, 204, 204));
        item4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item4MouseMoved(evt);
            }
        });
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });
        item4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel25.setText("Imprimir");
        item4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (6).png"))); // NOI18N
        item4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 50));

        jPanel1.setOpaque(false);
        pnlOptionPersona.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 30));

        add(pnlOptionPersona, java.awt.BorderLayout.LINE_END);

        pnlContainerFiltro.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlContainerFiltro.setMinimumSize(new java.awt.Dimension(800, 250));
        pnlContainerFiltro.setOpaque(false);
        pnlContainerFiltro.setPreferredSize(new java.awt.Dimension(800, 250));
        pnlContainerFiltro.setLayout(new java.awt.BorderLayout());

        PnlFiltro.setMaximumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setMinimumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setOpaque(false);
        PnlFiltro.setPreferredSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTextoFiltroUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtTextoFiltroUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        txtTextoFiltroUsuario.setOpaque(false);
        txtTextoFiltroUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTextoFiltroUsuarioCaretUpdate(evt);
            }
        });
        jPanel7.add(txtTextoFiltroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("BUSCAR");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 20));

        PnlFiltro.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 60));

        jcUsuarioFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcUsuarioFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona Filtro", "Nombre", "apellido", "Dni", "Codigo", "Inactivo" }));
        jcUsuarioFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcUsuarioFiltroItemStateChanged(evt);
            }
        });
        jcUsuarioFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUsuarioFiltroActionPerformed(evt);
            }
        });
        jcUsuarioFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcUsuarioFiltroPropertyChange(evt);
            }
        });
        jcUsuarioFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jcUsuarioFiltroVetoableChange(evt);
            }
        });
        PnlFiltro.add(jcUsuarioFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 30));

        pnlContainerFiltro.add(PnlFiltro, java.awt.BorderLayout.PAGE_START);

        jtUsuario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        jtUsuario.setRowHeight(25);
        jtUsuario.setSelectionBackground(new java.awt.Color(20, 110, 214));
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsuario);

        pnlContainerFiltro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(pnlContainerFiltro, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtApellidoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoUsuarioActionPerformed

    private void txtDniUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniUsuarioActionPerformed

    private void jcDepartamentoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDepartamentoUsuarioActionPerformed

    }//GEN-LAST:event_jcDepartamentoUsuarioActionPerformed

    private void txtTelefonoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoUsuarioActionPerformed

    private void txtUsuarioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioUsuarioActionPerformed

    private void jcUsuarioFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcUsuarioFiltroItemStateChanged

    }//GEN-LAST:event_jcUsuarioFiltroItemStateChanged

    private void jcUsuarioFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUsuarioFiltroActionPerformed

        try {
            if (jcUsuarioFiltro.getSelectedIndex() == 0) {
                tipoFiltro = 0;
                datoFiltro = "";
            } else {
                tipoFiltro = jcUsuarioFiltro.getSelectedIndex();
            }
            filtrar();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jcUsuarioFiltroActionPerformed

    private void filtrar() {
        datoFiltro = txtTextoFiltroUsuario.getText();
        txtTextoFiltroUsuario.requestFocus();
        txtTextoFiltroUsuario.setText("");
        try {
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void jcUsuarioFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcUsuarioFiltroPropertyChange

    }//GEN-LAST:event_jcUsuarioFiltroPropertyChange

    private void jcUsuarioFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jcUsuarioFiltroVetoableChange

    }//GEN-LAST:event_jcUsuarioFiltroVetoableChange

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código", "Nombre", "Apellido", "DNI", "Nacimiento", "Ubigeo", "Dirección", "Telefono", "Genero", "Usuario"};

        modeloTablaUsuario = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
//        productoD.listarProductoTabla(modeloTablaProducto, tipoFiltro, datoFiltro);
        usuarioC.listarUsuarioTabla(modeloTablaUsuario, tipoFiltro, datoFiltro);
        jtUsuario.setModel(modeloTablaUsuario);
    }


    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked

        int fila = jtUsuario.getSelectedRow(); // el nro de fila seleccionada

        if (fila >= 0) {

            //Botones
            desactivarBotones(2);
            hover.menu(-1);

            //Campos de formularios
            txtCodigoUsuario.setText(jtUsuario.getValueAt(fila, 0).toString());
            txtNombreUsuario.setText(jtUsuario.getValueAt(fila, 1).toString());
            txtApellidoUsuario.setText(jtUsuario.getValueAt(fila, 2).toString());
            txtDniUsuario.setText(jtUsuario.getValueAt(fila, 3).toString());

            try {
                jcaNacimientoUsuario.setDate(Date.valueOf(jtUsuario.getValueAt(fila, 4).toString()));
            } catch (Exception e) {
                jcaNacimientoUsuario.setDate(null);
            }

            ubigeoD.listarUbigeo(jcDepartamentoUsuario,
                    jcProvinciaUsuario,
                    jcDistritoUsuario,
                    jtUsuario.getValueAt(fila, 5).toString());
            txtUbigeoUsuario.setText(jtUsuario.getValueAt(fila, 5).toString());

            txtDireccionUsuario.setText(jtUsuario.getValueAt(fila, 6).toString());
            txtTelefonoUsuario.setText(jtUsuario.getValueAt(fila, 7).toString());

            for (Enumeration e = rdGrupoGenero.getElements(); e.hasMoreElements();) {
                JRadioButton b = (JRadioButton) e.nextElement();
                if (b.getActionCommand().equals(jtUsuario.getValueAt(fila, 8).toString())) {
                    b.setSelected(true);
                }

            }

            txtUsuarioUsuario.setText(jtUsuario.getValueAt(fila, 9).toString());

//            String unidad = jtPersona.getValueAt(fila, 2).toString();
//            for (int index = 0; index < jcUnidadMedida.getItemCount(); index++) {
//                if (jcUnidadMedida.getItemAt(index).getDESUNI().equals(unidad)) {
//                    jcUnidadMedida.setSelectedIndex(index);
//                    break;
//                };
//            }
//
//            txtPrecioProducto.setText(jtPersona.getValueAt(fila, 3).toString());
//
//            String categoria = jtPersona.getValueAt(fila, 4).toString();
//            for (int index = 0; index < jtPersona.getItemCount(); index++) {
//                if (jcCategoria.getItemAt(index).getDESCAT().equals(categoria)) {
//                    jcCategoria.setSelectedIndex(index);
//                    break;
//                };
//            }
        }


    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked
        if (item0.isEnabled()) {
            try {
                if (!usuarioC.validarExistenciaUsuario(txtDniUsuario.getText()) && usuarioC.validar()) {
                    usuarioC.cargarVariables();
                    usuarioC.guardarUsuario();
                    cargarTabla();
                    usuarioC.limpiarVariables();
                    hover.menu(-1);
                }
            } catch (Exception ex) {
                Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item0MouseClicked

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        if (item1.isEnabled()) {
            try {
                if (usuarioC.validarEditarUsuario()) {
                    usuarioC.cargarVariables();
                    usuarioC.editarUsuario();
                    cargarTabla();
                    usuarioC.limpiarVariables();
                    desactivarBotones(1);
                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseMoved
        hover.menu(2);
    }//GEN-LAST:event_item2MouseMoved

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        if (item2.isEnabled()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Seguro de eleminar?",
                    "Eliminación del registro",
                    JOptionPane.OK_CANCEL_OPTION);
            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    if (usuarioC.validarEditarUsuario()) {
                        usuarioC.cargarVariables();
                        usuarioC.eliminarUsuario();
                        cargarTabla();
                        usuarioC.limpiarVariables();
                        desactivarBotones(1);
                    }
                    hover.menu(-1);
                } catch (Exception ex) {
                    Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            hover.menu(-1);
        }
    }//GEN-LAST:event_item2MouseClicked

    private void item3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseMoved
        hover.menu(3);
    }//GEN-LAST:event_item3MouseMoved

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        if (item3.isEnabled()) {
            usuarioC.limpiarVariables();
            desactivarBotones(1);
            hover.menu(-1);
        }
    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseMoved
        hover.menu(4);
    }//GEN-LAST:event_item4MouseMoved

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_item4MouseClicked

    private void pnlOptionPersonaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionPersonaMouseMoved
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionPersonaMouseMoved

    private void jcDistritoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDistritoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDistritoUsuarioActionPerformed


    private void rdMasculinoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMasculinoUsuarioActionPerformed

    }//GEN-LAST:event_rdMasculinoUsuarioActionPerformed

    private void btnBuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseClicked
        if (txtDniUsuario.getText().length() == 8) {
            usuarioC.resPersona(txtDniUsuario.getText());
            txtUsuarioUsuario.setText(txtDniUsuario.getText());
            txtContraseñaUsuario.setText(txtDniUsuario.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese DNI (8 digitos)");
        }
    }//GEN-LAST:event_btnBuscarPersonaMouseClicked

    private void txtDireccionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionUsuarioActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed

    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnCredencialLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCredencialLoginMouseClicked
        try {
            if (!(txtContraseñaUsuario.getText().trim() == "") && txtContraseñaUsuario.getText().length()>=4) {
                usuarioC.cargarVariablesLogin();
                usuarioC.editarUsuarioLogin();
                cargarTabla();
                usuarioC.limpiarVariables();
                desactivarBotones(1);
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese contraseña (mayor a 4 digitos)");
            }
            hover.menu(-1);
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCredencialLoginMouseClicked

    private void txtDniUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniUsuarioKeyTyped
        char caracter = evt.getKeyChar();
        if (txtDniUsuario.getText().length() >= 8) {
            evt.consume();
        }

        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtDniUsuarioKeyTyped

    private void txtTextoFiltroUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTextoFiltroUsuarioCaretUpdate
        try {
            datoFiltro = txtTextoFiltroUsuario.getText();
            cargarTabla();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTextoFiltroUsuarioCaretUpdate

    private void jcDepartamentoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcDepartamentoUsuarioMouseClicked

    }//GEN-LAST:event_jcDepartamentoUsuarioMouseClicked

    private void jcDepartamentoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDepartamentoUsuarioItemStateChanged
        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                ubigeoD.listarProvinciaUbigeo(jcProvinciaUsuario, jcDepartamentoUsuario.getSelectedItem().toString());
                String CODUBI;
                UbigeoM ubigeo = (UbigeoM) jcDistritoUsuario.getSelectedItem();
                CODUBI = ubigeo.getIdUbi();
                txtUbigeoUsuario.setText(String.valueOf(CODUBI));
            }
        } catch (Exception ex) {
            System.out.println("Error en cboDptoItemState " + ex.getMessage());
        }
    }//GEN-LAST:event_jcDepartamentoUsuarioItemStateChanged

    private void jcProvinciaUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcProvinciaUsuarioItemStateChanged
        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                ubigeoD.listarDistritoUbigeo(jcDistritoUsuario, jcProvinciaUsuario.getSelectedItem().toString());
                String CODUBI;
                UbigeoM ubigeo = (UbigeoM) jcDistritoUsuario.getSelectedItem();
                CODUBI = ubigeo.getIdUbi();
                txtUbigeoUsuario.setText(String.valueOf(CODUBI));
            }
        } catch (Exception ex) {
            System.out.println("error en cargar el distrito en el cboProv " + ex.getMessage());
        }
    }//GEN-LAST:event_jcProvinciaUsuarioItemStateChanged

    private void jcDistritoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDistritoUsuarioItemStateChanged
        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                String CODUBI;
                UbigeoM ubigeo = (UbigeoM) jcDistritoUsuario.getSelectedItem();
                CODUBI = ubigeo.getIdUbi();
                txtUbigeoUsuario.setText(String.valueOf(CODUBI));
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_jcDistritoUsuarioItemStateChanged

    private void txtTelefonoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoUsuarioKeyTyped
        char caracter = evt.getKeyChar();
        if (txtTelefonoUsuario.getText().length() >= 9) {
            evt.consume();
        }

        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoUsuarioKeyTyped

    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(true);
                btnCredencialLogin.setEnabled(false);
                txtCodigoUsuario.setEnabled(true);
                txtUsuarioUsuario.setEnabled(true);

                break;

            case 2:
                item0.setEnabled(false);
                item1.setEnabled(true);
                item2.setEnabled(true);
                item3.setEnabled(true);
                item4.setEnabled(false);
                btnCredencialLogin.setEnabled(true);
                txtCodigoUsuario.setEnabled(false);
                txtUsuarioUsuario.setEnabled(false);

                break;

            case 3:
                item0.setEnabled(false);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(false);
                btnCredencialLogin.setEnabled(false);
                txtCodigoUsuario.setEnabled(false);
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFiltro;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCredencialLogin;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> jcDepartamentoUsuario;
    public static javax.swing.JComboBox<String> jcDistritoUsuario;
    public static javax.swing.JComboBox<String> jcProvinciaUsuario;
    public static javax.swing.JComboBox jcUsuarioFiltro;
    public static com.toedter.calendar.JDateChooser jcaNacimientoUsuario;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JPanel pnlApellido;
    private javax.swing.JPanel pnlApellido1;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPanel pnlContainerFiltro;
    private javax.swing.JPanel pnlDni;
    private javax.swing.JPanel pnlFechaNacimiento;
    private javax.swing.JPanel pnlGenero;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlOptionPersona;
    private javax.swing.JPanel pnlRuc1;
    private javax.swing.JPanel pnlRuc2;
    private javax.swing.JPanel pnlTelefono;
    private javax.swing.JPanel pnlUbicacion;
    private javax.swing.JPanel pnlUsuariosForm;
    public static javax.swing.JRadioButton rdFemeninoUsuario;
    public static javax.swing.ButtonGroup rdGrupoGenero;
    public static javax.swing.JRadioButton rdMasculinoUsuario;
    public static javax.swing.JTextField txtApellidoUsuario;
    public static javax.swing.JTextField txtCodigoUsuario;
    public static javax.swing.JPasswordField txtContraseñaUsuario;
    public static javax.swing.JTextField txtDireccionUsuario;
    public static javax.swing.JTextField txtDniUsuario;
    public static javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JTextField txtTelefonoUsuario;
    public static javax.swing.JTextField txtTextoFiltroUsuario;
    public static javax.swing.JLabel txtUbigeoUsuario;
    public static javax.swing.JTextField txtUsuarioUsuario;
    // End of variables declaration//GEN-END:variables
}
