/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

/**
 *
 * @author Jose Luis
 */
public class PnlUsuariosContainer extends javax.swing.JPanel {

    /**
     * Creates new form PnlUsuariosContainer
     */
    public PnlUsuariosContainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pnlApePaterno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPat = new javax.swing.JTextField();
        pnlApeMaterno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoMat = new javax.swing.JTextField();
        pnlRuc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoMat1 = new javax.swing.JTextField();
        pnlDni = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtApellidoMat2 = new javax.swing.JTextField();
        pnlUbicacion = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pnlDni1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoMat3 = new javax.swing.JTextField();
        pnlDni2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoMat4 = new javax.swing.JTextField();
        pnlDni3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtApellidoMat5 = new javax.swing.JTextField();
        pnlLogin = new javax.swing.JPanel();
        pnlRuc1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoMat6 = new javax.swing.JTextField();
        pnlRuc2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        pnlRuc3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        pnlDni4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        pnlDni5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        pnlDni6 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        pnlNombre.setOpaque(false);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        pnlNombre.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlNombre.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 30));

        add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 77, -1, -1));

        pnlApePaterno.setOpaque(false);
        pnlApePaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno");
        pnlApePaterno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtApellidoPat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPatActionPerformed(evt);
            }
        });
        pnlApePaterno.add(txtApellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 30));

        add(pnlApePaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 77, -1, -1));

        pnlApeMaterno.setOpaque(false);
        pnlApeMaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno");
        pnlApeMaterno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        txtApellidoMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMatActionPerformed(evt);
            }
        });
        pnlApeMaterno.add(txtApellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 30));

        add(pnlApeMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 77, -1, -1));

        pnlRuc.setOpaque(false);
        pnlRuc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setText("RUC");
        pnlRuc.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat1ActionPerformed(evt);
            }
        });
        pnlRuc.add(txtApellidoMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 30));

        add(pnlRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 163, -1, -1));

        pnlDni.setOpaque(false);
        pnlDni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("DNI");
        pnlDni.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat2ActionPerformed(evt);
            }
        });
        pnlDni.add(txtApellidoMat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        add(pnlDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 163, -1, -1));

        pnlUbicacion.setOpaque(false);
        pnlUbicacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        pnlUbicacion.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 136, 30));

        jComboBox2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlUbicacion.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 133, 30));

        jComboBox3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlUbicacion.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 133, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Ubicación");
        pnlUbicacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        add(pnlUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 163, 415, -1));

        pnlDni1.setOpaque(false);
        pnlDni1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Telefono 1");
        pnlDni1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat3ActionPerformed(evt);
            }
        });
        pnlDni1.add(txtApellidoMat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        add(pnlDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 60));

        pnlDni2.setOpaque(false);
        pnlDni2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Telefono 2");
        pnlDni2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat4ActionPerformed(evt);
            }
        });
        pnlDni2.add(txtApellidoMat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 30));

        add(pnlDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        pnlDni3.setOpaque(false);
        pnlDni3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Correo");
        pnlDni3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat5ActionPerformed(evt);
            }
        });
        pnlDni3.add(txtApellidoMat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 30));

        add(pnlDni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 270, -1));

        pnlLogin.setOpaque(false);
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRuc1.setOpaque(false);
        pnlRuc1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setText("Usuario");
        pnlRuc1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        txtApellidoMat6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoMat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMat6ActionPerformed(evt);
            }
        });
        pnlRuc1.add(txtApellidoMat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlLogin.add(pnlRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRuc2.setOpaque(false);
        pnlRuc2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Contraseña");
        pnlRuc2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jPasswordField1.setText("jPasswordField1");
        pnlRuc2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlLogin.add(pnlRuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pnlRuc3.setOpaque(false);
        pnlRuc3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Validar Contraseña");
        pnlRuc3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jPasswordField2.setText("jPasswordField1");
        pnlRuc3.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        pnlLogin.add(pnlRuc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        pnlDni4.setOpaque(false);
        pnlDni4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setText("Tipo");
        pnlDni4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jComboBox4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlDni4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 30));

        pnlLogin.add(pnlDni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 120, 60));

        add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 740, 60));

        pnlDni5.setOpaque(false);
        pnlDni5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setText("Empresa");
        pnlDni5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jComboBox5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9 ", "Item 10", "Item 11", "Item 12" }));
        pnlDni5.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 30));

        add(pnlDni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 60));

        pnlDni6.setOpaque(false);
        pnlDni6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Activo");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        pnlDni6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 30));

        add(pnlDni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPatActionPerformed

    private void txtApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMatActionPerformed

    private void txtApellidoMat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat1ActionPerformed

    private void txtApellidoMat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtApellidoMat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat3ActionPerformed

    private void txtApellidoMat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat4ActionPerformed

    private void txtApellidoMat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat5ActionPerformed

    private void txtApellidoMat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMat6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMat6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPanel pnlApeMaterno;
    private javax.swing.JPanel pnlApePaterno;
    private javax.swing.JPanel pnlDni;
    private javax.swing.JPanel pnlDni1;
    private javax.swing.JPanel pnlDni2;
    private javax.swing.JPanel pnlDni3;
    private javax.swing.JPanel pnlDni4;
    private javax.swing.JPanel pnlDni5;
    private javax.swing.JPanel pnlDni6;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlRuc;
    private javax.swing.JPanel pnlRuc1;
    private javax.swing.JPanel pnlRuc2;
    private javax.swing.JPanel pnlRuc3;
    private javax.swing.JPanel pnlUbicacion;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoMat1;
    private javax.swing.JTextField txtApellidoMat2;
    private javax.swing.JTextField txtApellidoMat3;
    private javax.swing.JTextField txtApellidoMat4;
    private javax.swing.JTextField txtApellidoMat5;
    private javax.swing.JTextField txtApellidoMat6;
    private javax.swing.JTextField txtApellidoPat;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
