/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.event.KeyEvent;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import sistema.controlador.ClienteC;
import static sistema.view.PnlUsuariosContainer.rdGrupoGenero;
import static sistema.view.PnlUsuariosContainer.txtDniUsuario;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlVentaContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    int nPnl, pnlActualClick;

    DefaultTableModel modeloTablaCliente;

    ClienteC clienteC = new ClienteC();
    Hover hover;

    public PnlVentaContainer() {

        initComponents();
        //Añanidor hover al menu
        nPnl = pnlOptionPersona.getComponentCount();
        hover = new Hover(nPnl, pnlOptionPersona);
        hover.menu(-1);
        try {
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlVentaContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBorder(new EmptyBorder(20, 40, 40, 40));
    }

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código", "Nombre", "Apellido", "DNI", "Genero", "Activo"};

        modeloTablaCliente = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
//        productoD.listarProductoTabla(modeloTablaProducto, tipoFiltro, datoFiltro);
        clienteC.listarClienteTabla(modeloTablaCliente, tipoFiltro, datoFiltro);
        jtVentas.setModel(modeloTablaCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrupoGenero = new javax.swing.ButtonGroup();
        pnlUsuariosForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlFiltro = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtClienteFiltro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcClienteFiltro = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVentas = new javax.swing.JTable();
        pnlOptionPersona = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        pnlUsuariosForm.setMaximumSize(new java.awt.Dimension(570, 400));
        pnlUsuariosForm.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlUsuariosForm.setOpaque(false);
        pnlUsuariosForm.setPreferredSize(new java.awt.Dimension(550, 300));
        pnlUsuariosForm.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 30, 110));

        PnlFiltro.setMaximumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setMinimumSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setOpaque(false);
        PnlFiltro.setPreferredSize(new java.awt.Dimension(570, 80));
        PnlFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClienteFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txtClienteFiltro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        txtClienteFiltro.setOpaque(false);
        txtClienteFiltro.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtClienteFiltroCaretUpdate(evt);
            }
        });
        jPanel7.add(txtClienteFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("BUSCAR");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 20));

        PnlFiltro.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 60));

        jcClienteFiltro.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jcClienteFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione filtro", "Nombre", "Apellido", "Dni", "Inactivos" }));
        jcClienteFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcClienteFiltroItemStateChanged(evt);
            }
        });
        jcClienteFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcClienteFiltroActionPerformed(evt);
            }
        });
        jcClienteFiltro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jcClienteFiltroPropertyChange(evt);
            }
        });
        jcClienteFiltro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jcClienteFiltroVetoableChange(evt);
            }
        });
        PnlFiltro.add(jcClienteFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 30));

        jPanel3.add(PnlFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pnlUsuariosForm.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jtVentas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtVentas.setGridColor(new java.awt.Color(255, 255, 255));
        jtVentas.setRowHeight(25);
        jScrollPane1.setViewportView(jtVentas);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlUsuariosForm.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(pnlUsuariosForm, java.awt.BorderLayout.CENTER);

        pnlOptionPersona.setBackground(new java.awt.Color(204, 102, 255));
        pnlOptionPersona.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionPersona.setOpaque(false);
        pnlOptionPersona.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionPersonaMouseMoved(evt);
            }
        });
        pnlOptionPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Vender");
        item0.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (1).png"))); // NOI18N
        item0.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setText("Editar");
        item1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag7.png"))); // NOI18N
        item1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        item2.setBackground(new java.awt.Color(204, 204, 204));
        item2.setEnabled(false);
        item2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item2MouseMoved(evt);
            }
        });
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });
        item2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setText("Eliminar");
        item2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        pnlOptionPersona.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        item3.setBackground(new java.awt.Color(204, 204, 204));
        item3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item3MouseMoved(evt);
            }
        });
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });
        item3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel25.setText("Imprimir");
        item3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (6).png"))); // NOI18N
        item3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 50));

        jPanel1.setOpaque(false);
        pnlOptionPersona.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 30));

        add(pnlOptionPersona, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void filtrar() {
        try {
            datoFiltro = txtClienteFiltro.getText();
            txtClienteFiltro.requestFocus();
            txtClienteFiltro.setText("");

            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked
        if (item0.isEnabled()) {
//            PnlEntradaContainer.jtmVentas.setSelectedIndex(1);
            
//            try {
//                if (!clienteC.validarExistenciaCliente(txtDniCliente.getText())) {
//                    if (clienteC.validar()) {
//                        clienteC.cargarVariables();
//                        clienteC.guardarCliente();
//                        cargarTabla();
//                        clienteC.limpiarVariables();
//                    }
//                }
//                hover.menu(-1);
//            } catch (Exception ex) {
//                Logger.getLogger(PnlVentaContainer.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_item0MouseClicked

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        if (item1.isEnabled()) {
            try {

                if (clienteC.validar()) {
                    clienteC.cargarVariables();
                    clienteC.editarCliente();
                    cargarTabla();
                    clienteC.limpiarVariables();
                    desactivarBotones(1);
                    hover.menu(-1);

                }

            } catch (Exception ex) {
                Logger.getLogger(PnlVentaContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseMoved
        hover.menu(2);
    }//GEN-LAST:event_item2MouseMoved

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        if (item2.isEnabled()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Seguro de eliminar",
                    "Eliminación del registro",
                    JOptionPane.OK_CANCEL_OPTION);

            if (opcion == JOptionPane.OK_OPTION) {
                try {
                    if (clienteC.validar()) {
                        clienteC.cargarVariables();
                        clienteC.eliminarCliente();
                        cargarTabla();
                        clienteC.limpiarVariables();
                        desactivarBotones(1);
                        hover.menu(-1);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(PnlVentaContainer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_item2MouseClicked

    private void item3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseMoved
        hover.menu(3);
    }//GEN-LAST:event_item3MouseMoved

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_item3MouseClicked

    private void pnlOptionPersonaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionPersonaMouseMoved
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionPersonaMouseMoved

    private void txtClienteFiltroCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtClienteFiltroCaretUpdate

        try {
            datoFiltro = txtClienteFiltro.getText();
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlClienteContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtClienteFiltroCaretUpdate

    private void jcClienteFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcClienteFiltroItemStateChanged

    }//GEN-LAST:event_jcClienteFiltroItemStateChanged

    private void jcClienteFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcClienteFiltroActionPerformed
        try {
            if (jcClienteFiltro.getSelectedIndex() == 0) {
                tipoFiltro = 0;
                datoFiltro = "";
            } else {
                tipoFiltro = jcClienteFiltro.getSelectedIndex();
            }
            filtrar();
        } catch (Exception ex) {
            Logger.getLogger(PnlUsuariosContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jcClienteFiltroActionPerformed

    private void jcClienteFiltroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jcClienteFiltroPropertyChange

    }//GEN-LAST:event_jcClienteFiltroPropertyChange

    private void jcClienteFiltroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jcClienteFiltroVetoableChange

    }//GEN-LAST:event_jcClienteFiltroVetoableChange


    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(true);

                break;

            case 2:
                item0.setEnabled(false);
                item1.setEnabled(true);
                item2.setEnabled(true);
                item3.setEnabled(false);


                break;

            case 3:
                item0.setEnabled(false);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFiltro;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox jcClienteFiltro;
    public static javax.swing.JTable jtVentas;
    private javax.swing.JPanel pnlOptionPersona;
    private javax.swing.JPanel pnlUsuariosForm;
    public static javax.swing.ButtonGroup rdGrupoGenero;
    public static javax.swing.JTextField txtClienteFiltro;
    // End of variables declaration//GEN-END:variables
}
