/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.view;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import sistema.controlador.ClienteC;
import sistema.controlador.EmpresaC;
import sistema.controlador.UsuarioC;
import sistema.controlador.VentaProductoC;
import static sistema.view.PnlEntradaContainer.pnlVentaProducto;
import utilidad.Hover;

/**
 *
 * @author Jose Luis
 */
public class PnlVentaProductoContainer extends javax.swing.JPanel {

    private int tipoFiltro = 0;
    private String datoFiltro = "";

    VentaProductoC ventaProductoC = new VentaProductoC();
    ClienteC clienteC = new ClienteC();

    int nPnl, pnlActualClick;
    DefaultTableModel modeloTablaVentaProducto;

    UsuarioC usuarioC = new UsuarioC();
    EmpresaC empresaC = new EmpresaC();
    Hover hover;

    public PnlVentaProductoContainer() {

        initComponents();
        //Añanidor hover al menu
        nPnl = pnlOptionPersona.getComponentCount();
        hover = new Hover(nPnl, pnlOptionPersona);
        desactivarBotones(1);
        hover.menu(-1);
        try {
            this.cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(PnlVentaProductoContainer.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setBorder(new EmptyBorder(20, 40, 40, 40));
        jpVistaPrecioVenta.setBorder(new EmptyBorder(20, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGrupoGenero = new javax.swing.ButtonGroup();
        rdGRupoTipo = new javax.swing.ButtonGroup();
        jpVistaCabeceraVenta = new javax.swing.JPanel();
        jpVistaCliente = new javax.swing.JPanel();
        btnBuscarClienteVentaProducto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlDatoClienteVentaProducto = new javax.swing.JLabel();
        jcTipoVentaProducto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDniRucClienteVenta = new javax.swing.JTextField();
        jlCodigoClienteVentaProducto = new javax.swing.JLabel();
        jlCodigoVentaProducto = new javax.swing.JLabel();
        jpVistaCuerpoVenta = new javax.swing.JPanel();
        jpVistaAgregarProducto = new javax.swing.JPanel();
        pnlOptionPersona = new javax.swing.JPanel();
        item0 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        item1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jsCantidadVenta = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcaFechaVentaProducto = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jpVistaTablaProductoVenta = new javax.swing.JPanel();
        Scroll = new javax.swing.JScrollPane();
        jtVentaProducto = new javax.swing.JTable();
        jpVistaPrecioVenta = new javax.swing.JPanel();
        jpVistaPrecio = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlSubTotalProducto = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jlIgbProducto = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jlTotalProducto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        jpVistaCabeceraVenta.setOpaque(false);
        jpVistaCabeceraVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpVistaCliente.setOpaque(false);
        jpVistaCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarClienteVentaProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnBuscarClienteVentaProducto.setText("Buscar");
        btnBuscarClienteVentaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteVentaProductoMouseClicked(evt);
            }
        });
        jpVistaCliente.add(btnBuscarClienteVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cliente");
        jpVistaCliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        jlDatoClienteVentaProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlDatoClienteVentaProducto.setForeground(new java.awt.Color(102, 102, 102));
        jlDatoClienteVentaProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDatoClienteVentaProducto.setText("Jose Luis Quispe Luyo");
        jlDatoClienteVentaProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpVistaCliente.add(jlDatoClienteVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 350, 30));

        jcTipoVentaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));
        jcTipoVentaProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcTipoVentaProductoItemStateChanged(evt);
            }
        });
        jpVistaCliente.add(jcTipoVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Tipo de Venta");
        jpVistaCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        txtDniRucClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniRucClienteVentaKeyTyped(evt);
            }
        });
        jpVistaCliente.add(txtDniRucClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 30));
        jpVistaCliente.add(jlCodigoClienteVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 20));

        jlCodigoVentaProducto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jpVistaCliente.add(jlCodigoVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 90, 20));

        jpVistaCabeceraVenta.add(jpVistaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 750, 80));

        add(jpVistaCabeceraVenta, java.awt.BorderLayout.PAGE_START);

        jpVistaCuerpoVenta.setOpaque(false);
        jpVistaCuerpoVenta.setLayout(new java.awt.BorderLayout());

        jpVistaAgregarProducto.setOpaque(false);
        jpVistaAgregarProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOptionPersona.setBackground(new java.awt.Color(204, 102, 255));
        pnlOptionPersona.setMaximumSize(new java.awt.Dimension(150, 300));
        pnlOptionPersona.setMinimumSize(new java.awt.Dimension(690, 100));
        pnlOptionPersona.setOpaque(false);
        pnlOptionPersona.setPreferredSize(new java.awt.Dimension(690, 100));
        pnlOptionPersona.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlOptionPersonaMouseMoved(evt);
            }
        });
        pnlOptionPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        item0.setBackground(new java.awt.Color(204, 204, 204));
        item0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                item0MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item0MouseMoved(evt);
            }
        });
        item0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item0MouseClicked(evt);
            }
        });
        item0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Agregar");
        item0.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (1).png"))); // NOI18N
        item0.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        item1.setBackground(new java.awt.Color(204, 204, 204));
        item1.setEnabled(false);
        item1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item1MouseMoved(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel19.setText("Editar");
        item1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag7.png"))); // NOI18N
        item1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 50));

        item2.setBackground(new java.awt.Color(204, 204, 204));
        item2.setEnabled(false);
        item2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item2MouseMoved(evt);
            }
        });
        item2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2MouseClicked(evt);
            }
        });
        item2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel21.setText("Eliminar");
        item2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (4).png"))); // NOI18N
        item2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        pnlOptionPersona.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 50));

        item3.setBackground(new java.awt.Color(204, 204, 204));
        item3.setEnabled(false);
        item3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item3MouseMoved(evt);
            }
        });
        item3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3MouseClicked(evt);
            }
        });
        item3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel23.setText("Registrar venta");
        item3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (2).png"))); // NOI18N
        item3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 30, 50));

        pnlOptionPersona.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 170, 50));

        item4.setBackground(new java.awt.Color(204, 204, 204));
        item4.setEnabled(false);
        item4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                item4MouseMoved(evt);
            }
        });
        item4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4MouseClicked(evt);
            }
        });
        item4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel25.setText("Imprimir venta");
        item4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto/price-tag (6).png"))); // NOI18N
        item4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlOptionPersona.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 170, 50));

        jpVistaAgregarProducto.add(pnlOptionPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 820, 70));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsCantidadVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(jsCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));
        jPanel1.add(jcaFechaVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 70, 30));

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jpVistaAgregarProducto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 70));

        jpVistaCuerpoVenta.add(jpVistaAgregarProducto, java.awt.BorderLayout.PAGE_START);

        jpVistaTablaProductoVenta.setLayout(new java.awt.BorderLayout());

        Scroll.setBackground(new java.awt.Color(255, 255, 255));
        Scroll.setToolTipText("");
        Scroll.setOpaque(false);

        jtVentaProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jtVentaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtVentaProducto.setGridColor(new java.awt.Color(255, 255, 255));
        jtVentaProducto.setRowHeight(25);
        jtVentaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVentaProductoMouseClicked(evt);
            }
        });
        jtVentaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtVentaProductoKeyPressed(evt);
            }
        });
        Scroll.setViewportView(jtVentaProducto);

        jpVistaTablaProductoVenta.add(Scroll, java.awt.BorderLayout.CENTER);

        jpVistaCuerpoVenta.add(jpVistaTablaProductoVenta, java.awt.BorderLayout.CENTER);

        jpVistaPrecioVenta.setOpaque(false);
        jpVistaPrecioVenta.setLayout(new java.awt.BorderLayout());

        jpVistaPrecio.setMinimumSize(new java.awt.Dimension(500, 60));
        jpVistaPrecio.setOpaque(false);
        jpVistaPrecio.setPreferredSize(new java.awt.Dimension(500, 70));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 255, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sub total");
        jLabel10.setOpaque(true);
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jlSubTotalProducto.setBackground(new java.awt.Color(204, 255, 153));
        jlSubTotalProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSubTotalProducto.setText("0.00");
        jlSubTotalProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(255, 255, 255)));
        jlSubTotalProducto.setOpaque(true);
        jPanel9.add(jlSubTotalProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 40));

        jpVistaPrecio.add(jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(153, 255, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("IGV");
        jLabel12.setOpaque(true);
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jlIgbProducto.setBackground(new java.awt.Color(153, 255, 153));
        jlIgbProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIgbProducto.setText("18%");
        jlIgbProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(255, 255, 255)));
        jlIgbProducto.setOpaque(true);
        jPanel10.add(jlIgbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 40));

        jpVistaPrecio.add(jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(102, 255, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total");
        jLabel14.setOpaque(true);
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        jlTotalProducto.setBackground(new java.awt.Color(102, 255, 102));
        jlTotalProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTotalProducto.setText("0.00");
        jlTotalProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(255, 255, 255)));
        jlTotalProducto.setOpaque(true);
        jPanel11.add(jlTotalProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 40));

        jpVistaPrecio.add(jPanel11);

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Calcular :D");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(100, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 40));
        jButton2.setOpaque(false);
        jButton2.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jpVistaPrecio.add(jButton2);

        jpVistaPrecioVenta.add(jpVistaPrecio, java.awt.BorderLayout.CENTER);

        jpVistaCuerpoVenta.add(jpVistaPrecioVenta, java.awt.BorderLayout.PAGE_END);

        add(jpVistaCuerpoVenta, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla() throws Exception {
        String columna[] = new String[]{"Código", "Producto", "Unidad", "Precio", "Cantidad", "P. Venta"};
        modeloTablaVentaProducto = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ventaProductoC.listarVentaProductoTabla(modeloTablaVentaProducto, tipoFiltro, datoFiltro);
        jtVentaProducto.setModel(modeloTablaVentaProducto);
    }

    private void item0MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseDragged

    }//GEN-LAST:event_item0MouseDragged

    private void item0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseMoved
        hover.menu(0);
    }//GEN-LAST:event_item0MouseMoved

    private void item0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item0MouseClicked
        PnlEntradaContainer.pnlVentaProducto.getComponent(1).setVisible(true);
        PnlEntradaContainer.pnlVentaProducto.getComponent(0).setVisible(false);
        PnlEntradaContainer.pnlVentaProducto.add(PnlEntradaContainer.pnlVentaProducto.getComponent(1), 1);
        PnlEntradaContainer.pnlVentaProducto.validate();
        hover.menu(-1);
    }//GEN-LAST:event_item0MouseClicked

    private void item1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseMoved
        hover.menu(1);
    }//GEN-LAST:event_item1MouseMoved

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        editSelectedRows(jtVentaProducto);
        desactivarBotones(1);
        hover.menu(-1);
    }//GEN-LAST:event_item1MouseClicked

    private void item2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseMoved
        hover.menu(2);
    }//GEN-LAST:event_item2MouseMoved

    private void item2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2MouseClicked
        removeSelectedRows(jtVentaProducto);
    }//GEN-LAST:event_item2MouseClicked

    private void removeSelectedRows(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int[] rows = table.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            model.removeRow(rows[i] - i);
        }
    }

    private void editSelectedRows(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int[] rows = table.getSelectedRows();
        int fila = jtVentaProducto.getSelectedRow();

        model.setValueAt(String.valueOf(jsCantidadVenta.getValue()), fila, 4);
        double precioProducto = Double.parseDouble(model.getValueAt(fila, 3).toString());

        int cantidadProducto = Integer.parseInt(model.getValueAt(fila, 4).toString());

        double precioTotal = cantidadProducto * precioProducto;

        model.setValueAt(String.valueOf(jsCantidadVenta.getValue()), fila, 4);
        System.out.println(precioTotal);
        model.setValueAt(String.format("%.2f", precioTotal), fila, 5);

        JOptionPane.showMessageDialog(null, "Cantidad actualizada");

    }

    private void calcularPrecioVentaRows(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        double precio = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            precio += Double.parseDouble(model.getValueAt(i, 5).toString());
            jlSubTotalProducto.setText(String.format("%.2f", precio));
        }

//        for (int i = 0; i < rows.length; i++) {
//            model.removeRow(rows[i] - i);
//        }
    }


    private void item3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseMoved
        hover.menu(3);
    }//GEN-LAST:event_item3MouseMoved

    private void item3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3MouseClicked

    }//GEN-LAST:event_item3MouseClicked

    private void item4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseMoved
        hover.menu(4);
    }//GEN-LAST:event_item4MouseMoved

    private void item4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_item4MouseClicked

    private void pnlOptionPersonaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOptionPersonaMouseMoved
        hover.menu(-1);
    }//GEN-LAST:event_pnlOptionPersonaMouseMoved

    private void jtVentaProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVentaProductoKeyPressed

    }//GEN-LAST:event_jtVentaProductoKeyPressed

    private void jtVentaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVentaProductoMouseClicked
        int fila = jtVentaProducto.getSelectedRow(); // el nro de fila seleccionada
        if (fila >= 0) {
            //Botones
            desactivarBotones(2);
            hover.menu(-1);
            jsCantidadVenta.setValue(Integer.parseInt(jtVentaProducto.getValueAt(fila, 4).toString()));
        }
    }//GEN-LAST:event_jtVentaProductoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        calcularPrecioVentaRows(jtVentaProducto);
        double SubTotal = Double.parseDouble(jlSubTotalProducto.getText());
        double precioTotalProducto = (SubTotal + (SubTotal * 0.18));
        if (precioTotalProducto > 0) {
            desactivarBotones(3);
        } else {
            desactivarBotones(1);
        }
        hover.menu(-1);
        jlTotalProducto.setText(String.format("%.2f", precioTotalProducto));
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnBuscarClienteVentaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteVentaProductoMouseClicked
        if (btnBuscarClienteVentaProducto.isEnabled()) {
            try {
                if (jcTipoVentaProducto.getSelectedIndex() == 0) {
                    if (clienteC.validarExistenciaCliente(txtDniRucClienteVenta.getText())) {
                        ventaProductoC.cargarClienteVentaProducto(txtDniRucClienteVenta.getText());
//                    ventaProductoC.cargarVariables();
                    } else {
                        JOptionPane.showMessageDialog(null, "Registre al cliente");
                    }
                } else {
                    if (empresaC.validarExistenciaEmpresa(txtDniRucClienteVenta.getText())) {
                        ventaProductoC.cargarClienteVentaProducto(txtDniRucClienteVenta.getText());
//                    ventaProductoC.cargarVariables();
                    } else {
                        JOptionPane.showMessageDialog(null, "Registre al cliente");
                    }
                }
                hover.menu(-1);
            } catch (Exception ex) {
                Logger.getLogger(PnlClienteContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarClienteVentaProductoMouseClicked

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed

    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (ventaProductoC.validar()) {
            ventaProductoC.cargarVariables();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void txtDniRucClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniRucClienteVentaKeyTyped
        char caracter = evt.getKeyChar();
        int tipoVenta = jcTipoVentaProducto.getSelectedIndex();

        if (tipoVenta == 0) {
            if (txtDniRucClienteVenta.getText().length() >= 8) {
                evt.consume();
            }

        } else {
            if (txtDniRucClienteVenta.getText().length() >= 11) {
                evt.consume();
            }
        }

        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtDniRucClienteVentaKeyTyped

    private void jcTipoVentaProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcTipoVentaProductoItemStateChanged
        ventaProductoC.limpiarVariable();
    }//GEN-LAST:event_jcTipoVentaProductoItemStateChanged

    private void desactivarBotones(int tipo) {

        switch (tipo) {
            case 1:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(false);
                item4.setEnabled(false);

                break;

            case 2:
                item0.setEnabled(true);
                item1.setEnabled(true);
                item2.setEnabled(true);
                item3.setEnabled(false);
                item4.setEnabled(false);

                break;

            case 3:
                item0.setEnabled(true);
                item1.setEnabled(false);
                item2.setEnabled(false);
                item3.setEnabled(true);
                item4.setEnabled(true);
                break;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    public static javax.swing.JButton btnBuscarClienteVentaProducto;
    private javax.swing.JPanel item0;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JComboBox<String> jcTipoVentaProducto;
    public static com.toedter.calendar.JDateChooser jcaFechaVentaProducto;
    public static javax.swing.JLabel jlCodigoClienteVentaProducto;
    public static javax.swing.JLabel jlCodigoVentaProducto;
    public static javax.swing.JLabel jlDatoClienteVentaProducto;
    private javax.swing.JLabel jlIgbProducto;
    private javax.swing.JLabel jlSubTotalProducto;
    private javax.swing.JLabel jlTotalProducto;
    private javax.swing.JPanel jpVistaAgregarProducto;
    private javax.swing.JPanel jpVistaCabeceraVenta;
    private javax.swing.JPanel jpVistaCliente;
    private javax.swing.JPanel jpVistaCuerpoVenta;
    private javax.swing.JPanel jpVistaPrecio;
    private javax.swing.JPanel jpVistaPrecioVenta;
    private javax.swing.JPanel jpVistaTablaProductoVenta;
    private javax.swing.JSpinner jsCantidadVenta;
    public static javax.swing.JTable jtVentaProducto;
    private javax.swing.JPanel pnlOptionPersona;
    private javax.swing.ButtonGroup rdGRupoTipo;
    private javax.swing.ButtonGroup rdGrupoGenero;
    public static javax.swing.JTextField txtDniRucClienteVenta;
    // End of variables declaration//GEN-END:variables
}
