use sistema_venta;

select * from persona;

DELIMITER //
CREATE PROCEDURE INSERTAR_CLIENTE(
	IN	
	_NOMPER	varchar(80),
	_APEPER	varchar(80),
	_RUCDNIPER varchar(11),
	_GENPER	char(1),
	_TIPPER	char(1),
	_ESTAPER char(1)
)BEGIN

    INSERT INTO PERSONA
		(NOMPER,APEPER,RUCDNIPER,GENPER,TIPPER,ESTAPER)
    VALUES
		(_NOMPER,_APEPER,_RUCDNIPER,_GENPER,_TIPPER,_ESTAPER);
        
END;


CALL INSERTAR_CLIENTE('Jose Luis', 'Quispe Luyo', '22345677','M','C','A');

//DELIMITER ;*/


DELIMITER //
CREATE PROCEDURE EDITAR_CLIENTE(
	IN	
    _CODPER int(11),
	_NOMPER	varchar(80),
	_APEPER	varchar(80),
	_RUCDNIPER varchar(11),
	_GENPER	char(1),
	_TIPPER	char(1),
	_ESTAPER char(1)
    
)BEGIN
	Update 
		PERSONA 
        
		set NOMPER=_NOMPER, 
			APEPER=_APEPER, 
            RUCDNIPER=_RUCDNIPER,
            GENPER=_GENPER,
            TIPPER=_TIPPER,
            ESTAPER=_ESTAPER
		where CODPER=_CODPER;
END;

CALL EDITAR_CLIENTE(4,'Jose Luis', 'Quispe Luyo', '22345677','M','C','A');
			
//DELIMITER ;*/



DELIMITER //
CREATE PROCEDURE ELIMINAR_CLIENTE(_CODPER int, _ESTAPER char(1))
BEGIN

	Update 
		PERSONA 
		set
            ESTAPER=_ESTAPER
            
		where CODPER=_CODPER;
    
END;

CALL ELIMINAR_CLIENTE(4, 'B');

//DELIMITER ;*/


DELIMITER //
CREATE PROCEDURE VERIFICAR_EXISTENCIA_CLIENTE(_RUCDNIPER varchar(30))
BEGIN

    SELECT RUCDNIPER FROM PERSONA WHERE RUCDNIPER = _RUCDNIPER and TIPPER = 'C';
		
END;

CALL VERIFICAR_EXISTENCIA_CLIENTE('22345677');

//DELIMITER ;*/


DELIMITER //
CREATE PROCEDURE MOSTRAR_CLIENTE()
BEGIN

    SELECT CODPER, NOMPER,APEPER,RUCDNIPER,GENPER
		FROM PERSONA
		WHERE ESTAPER = 'A' AND TIPPER = 'C';
		
END;

CALL MOSTRAR_CLIENTE();

//DELIMITER ;*/


drop procedure FILTRAR_CLIENTE;

DELIMITER //
CREATE PROCEDURE FILTRAR_CLIENTE(

	_opcion char(1),
    _dato varchar (100)
    
)BEGIN
	IF _opcion = '1' THEN
    
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,GENPER
			FROM PERSONA
		WHERE NOMPER like _dato AND ESTAPER = 'A' AND TIPPER = 'C';
        
	 ELSEIF _opcion = '2' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,GENPER
			FROM PERSONA
		WHERE APEPER like _dato AND ESTAPER = 'A' AND TIPPER = 'C';
        
     ELSEIF _opcion = '3' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,GENPER
			FROM PERSONA
		WHERE RUCDNIPER like _dato AND ESTAPER = 'A' AND TIPPER = 'C';
        
	END IF;
END;

CALL FILTRAR_CLIENTE('1', '%%');

//DELIMITER ;*/


