
describe PERSONA;

DELIMITER //
CREATE PROCEDURE INSERTAR_USUARIO(
	IN	
	_NOMPER	varchar(80),
	_APEPER	varchar(80),
	_RUCDNIPER varchar(11),
	_FECNAC	date,
	_UBIPER	char(6),
	_DIRPER	varchar(30),
	_TELPER char(9),
	_GENPER	char(1),
	_USEPER	varchar(30),
	_CONPER	varchar(100),
	_TIPPER	char(1),
	_ESTAPER char(1)
)BEGIN

    INSERT INTO PERSONA
		(NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER,USEPER,CONPER,TIPPER,ESTAPER)
    VALUES
		(_NOMPER,_APEPER,_RUCDNIPER,_FECNAC,_UBIPER,_DIRPER,_TELPER,_GENPER,_USEPER,_CONPER,_TIPPER,_ESTAPER);
        
END;

CALL INSERTAR_USUARIO('Jose Luis', 'Quispe Luyo', '12345677','2000/11/19','140409','Mz. 10 Lt 10','123456789','M', 'Jose1',sha1(md5('contra')),'U','A');

//DELIMITER ;*/


DELIMITER //
CREATE PROCEDURE EDITAR_USUARIO_DATOS(
	IN	
    _CODPER int(11),
	_NOMPER	varchar(80),
	_APEPER	varchar(80),
	_RUCDNIPER varchar(11),
	_FECNAC	date,
	_UBIPER	char(6),
	_DIRPER	varchar(30),
	_TELPER char(9),
	_GENPER	char(1),
	_TIPPER	char(1),
	_ESTAPER char(1)
    
)BEGIN
	Update 
		PERSONA 
        
		set NOMPER=_NOMPER, 
			APEPER=_APEPER, 
            RUCDNIPER=_RUCDNIPER,
            FECNAC=_FECNAC,
            UBIPER=_UBIPER,
			DIRPER=_DIRPER,
            TELPER=_TELPER,
            GENPER=_GENPER,
            TIPPER=_TIPPER,
            ESTAPER=_ESTAPER
		where CODPER=_CODPER;
END;

CALL EDITAR_USUARIO_DATOS(3,'Jose Luis3', 'Quispe Luyo', '12345678900','2000/11/19','140409',
							'Mz. 10 Lt 10','123456789','M','U','A');
				
//DELIMITER ;*/

select * from persona;
DELIMITER //
CREATE PROCEDURE EDITAR_USUARIO_LOGIN(
	IN	
    _CODPER int(11),
	_USEPER varchar(30),
	_CONPER varchar (100)
    
)BEGIN
	Update 
		PERSONA 
		set
            USEPER=_USEPER,
            CONPER=_CONPER
            
		where CODPER=_CODPER;
END;

CALL EDITAR_USUARIO_LOGIN(3,'Jose1',sha1(md5('contra')));

//DELIMITER ;*/

select * from persona;

DELIMITER //
CREATE PROCEDURE ELIMINAR_USUARIO(_CODPER int, _ESTAPER char(1))
BEGIN

	Update 
		PERSONA 
		set
            ESTAPER=_ESTAPER
            
		where CODPER=_CODPER;
    
END;

CALL ELIMINAR_USUARIO(3, 'B');

//DELIMITER ;*/


DELIMITER //
CREATE PROCEDURE VERIFICAR_EXISTENCIA_USUARIO_LOGIN(_USEPER varchar(30))
BEGIN

    SELECT USEPER FROM PERSONA WHERE USEPER=_USEPER and TIPPER = 'U';
		
END;

CALL VERIFICAR_EXISTENCIA_USUARIO_LOGIN('Jose');

//DELIMITER ;*/



DELIMITER //
CREATE PROCEDURE VERIFICAR_EXISTENCIA_USUARIO(_RUCDNIPER varchar(30))
BEGIN

    SELECT RUCDNIPER FROM PERSONA WHERE RUCDNIPER = _RUCDNIPER and TIPPER = 'U';
		
END;

CALL VERIFICAR_EXISTENCIA_USUARIO('12345678900');

//DELIMITER ;*/



DELIMITER //
CREATE PROCEDURE MOSTRAR_USUARIO()
BEGIN

    SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
		FROM PERSONA
		WHERE ESTAPER = 'A' AND TIPPER = 'U';
		
END;

CALL MOSTRAR_USUARIO();

//DELIMITER ;*/


drop procedure FILTRAR_USUARIO;

DELIMITER //
CREATE PROCEDURE FILTRAR_USUARIO(

	_opcion char(1),
    _dato varchar (100)
    
)BEGIN
	IF _opcion = '1' THEN
    
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
			FROM PERSONA
		WHERE NOMPER like _dato AND ESTAPER = 'A' AND TIPPER = 'U';
        
	 ELSEIF _opcion = '2' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
			FROM PERSONA
		WHERE APEPER like _dato AND ESTAPER = 'A' AND TIPPER = 'U';
        
     ELSEIF _opcion = '3' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
			FROM PERSONA
		WHERE RUCDNIPER like _dato AND ESTAPER = 'A' AND TIPPER = 'U';
        
	 ELSEIF _opcion = '4' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
			FROM PERSONA
		WHERE CODPER like _dato AND ESTAPER = 'A' AND TIPPER = 'U';
        
	 ELSEIF _opcion = '5' THEN
		SELECT CODPER, NOMPER,APEPER,RUCDNIPER,FECNAC,UBIPER,DIRPER,TELPER,GENPER, USEPER
			FROM PERSONA
		WHERE ESTAPER = 'B' AND TIPPER = 'U';
        
	END IF;
END;

CALL FILTRAR_USUARIO('5', '%%');

//DELIMITER ;*/



